# Generated by Django 2.1.2 on 2018-11-13 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroes',
            options={'verbose_name_plural': 'Heroes'},
        ),
    ]
