# Generated by Django 2.1.2 on 2018-11-16 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HeroWeapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='heroes',
            name='types',
        ),
        migrations.DeleteModel(
            name='HeroType',
        ),
        migrations.AddField(
            model_name='heroes',
            name='movement',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='heroes.HeroMovement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heroes',
            name='weapon',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='heroes.HeroWeapon'),
            preserve_default=False,
        ),
    ]
