# Generated by Django 2.1.2 on 2018-11-16 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0002_auto_20181116_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heroes.HeroMovement')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heroes.HeroWeapon')),
            ],
        ),
        migrations.RemoveField(
            model_name='heroes',
            name='movement',
        ),
        migrations.RemoveField(
            model_name='heroes',
            name='weapon',
        ),
        migrations.AddField(
            model_name='heroes',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='heroes.HeroType'),
        ),
    ]
