# Generated by Django 2.1.2 on 2018-11-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0002_auto_20181113_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.PositiveIntegerField()),
                ('attack', models.PositiveIntegerField()),
                ('speed', models.PositiveIntegerField()),
                ('defense', models.PositiveIntegerField()),
                ('resistance', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HeroType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement', models.CharField(max_length=20)),
                ('weapon', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='heroes',
            name='stats',
        ),
        migrations.RemoveField(
            model_name='heroes',
            name='types',
        ),
    ]
