# Generated by Django 2.1.2 on 2018-11-13 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0003_auto_20181113_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroes',
            name='stats',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='heroes.HeroStat'),
        ),
        migrations.AddField(
            model_name='heroes',
            name='types',
            field=models.ManyToManyField(to='heroes.HeroType'),
        ),
    ]
